<%
if ((session.getAttribute("user") == null)) {
%>
You are not logged in<br/>
<a href="login.jsp">Please Login</a>
<%} else {
%>
Welcome <%=session.getAttribute("user")%> 
<a href='logout.jsp'>Log out</a>
<%
}
%>

<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head> 
<meta charset="UTF-8">
<title>Insert</title> 
<link href="/railwaysystem/css/style.css" rel="stylesheet">
</head>
<body >
<h1>Welcome manager</h1>
		
		<div> 
				
				<div>
					<form method='get' action ='manager'>
							<input type='hidden' name='action' value='update'>
							<input  type= 'submit' value ="Update a customer representative's informations"  >
					</form>    
				</div>
				  
				<div> <a href=''> Get monthly sales report</a>  </div>
				
				<div>
					<form method='get' action ='manager'>
							<input type='hidden' name='action' value='get_reservation'>
							<input  type= 'submit' value ='Get list of reservations by transit line or by customer name'  >
					</form>    
				</div>
				
				<div> <a href=''> Produce the total revenue generated by a particular transit line, or customer</a>  </div>
				
				<div> 
					<form method='get' action ='manager'>
						<input type='hidden' name='action' value='highest_revenue'>
						<input  type= 'submit' value ='Get the customer who generated the most total revenue '  >
					</form>  
				
				</div>
				
				<div> 
					<form method='get' action ='manager'>
						<input type='hidden' name='action' value='active'>
						<input  type= 'submit' value ='Produce a list of the 5 most active transit lines'  >
					</form>  
				</div>
		
		</div>
</body>
</html>